# Discussion 

## Weigert Creek - PSCIS crossing 197534
Fish were captured upstream of the highway only to within the first 300m upstream of the ford on the Weigert Creek FSR that is located at an elevation of 1320m approximately 1.5km above Highway 43.  Above this location, although significant electrofishing effort was conducted no fish were captured. 

<br>

Although physical habitat characteristics (pool depths, presence of gravels/LWD, etc) appeared suitable to support westslope cutthrout trout in Reach 3 and in fact had more complexity than lower reaches due to large woody debris abundance and percent composition of pools, there were no fish captured in the area of Reach 3 sampled. This was not expected, as the entire section of stream between where was sampled in Reach 3 and where fish were captured in Reach 2 was surveyed and although some smaller large woody debris jams from 60 - 70cm were observed, no permanent barriers were present that we would expect to block upstream migration of adult westslope cutthrout trout. 

<br>

Cold water temperatures have been demonstrated to provide recruitment bottlenecks in early life stages of westslope cutthrout trout with days during the growing season above an average of 5$^\circ$C a key determinant in growth and subsequent fry survival during overwintering [@coleman_fausch2007ColdSummera; @coleman_fausch2007ColdSummer]. Furthermore, ongoing programs of temperature modelling for Teck in the region are revealing that the single best predictor variable of westslope cutthrout trout density in is temperature (pers. comm. Joe Thorley, Poisson Consulting Ltd.). @coleman_fausch2007ColdSummera define the start of the growing season as the beginning of the first week that average stream temperatures exceed and remain above 5$^\circ$C in the spring and the end of the growing season as the last day of the first week that average stream temperature drops below 4$^\circ$C. Although there is some potential that the lack of fish captured in Reach 3 could be related to the potentially hindered upstream migration at the highway culverts, temperature information taken within Reach 1 at approximately 20m upstream of Highway 43 at an elevation of 1260m demonstrated that temperatures close to 5$^\circ$C prevailed at this elevation from May - November 2023 indicating that temperatures at higher elevations in the watershed (ie. Reach 3 begins at 1460m) may preclude fish use of these areas. Subsequently, cold temperatures during the growing season even at locations upstream of the Highway where only adult fish were captured could be an indication that  adult fish are the only life stage able to survive year to year in these locations and leads us to wonder if fry in these cold systems may migrate downstream upon emergence seeking warmer rearing temperatures in the first years of life. 

<br>

Although difficult to determine cause, presence of only adult fish upstream of the Highway 43 crossing on Weigert Creek and a significant increase in the density of adult fish upstream when compared to downstream could be related to swim speed ability and the associated increased potential for larger fish to migrate from downstream to upstream of the culvert. The fact that fish of the size captured (up to over 30cm long) were within this system so late in the year indicates that they were resident and not merely in the system to spawn.  This is particularly interesting as we would not have expected fish of this size to be resident within a system of this relatively small size (average channel width in Reach 2 of 5.5m).

<br>

Recommendations going forward include:

  * To understand current patterns of movement within the stream, conduct electrofishing within currently fish bearing reaches both upstream and downstream of the crossing, pit tag all captured fish (>50mm long) and resample in future years.  As there are extensive tagging programs throughout the Elk River watershed includeing tagging programs conducted by Nupqu as well as numerous guideing companies, this could give an idea of fish movement not only within Weigert Creek but also allow confirmation of habitat use within the mainstem of the Elk River by fish tagged in Weigert Creek as well as of utilization of habitat in Weigert Creek by fish originally tagged in the Elk River.
  
  * Collect Weigert Creek temperature data at points known to support westslope cutthrout trout (ie. immediately upstream of the highway and adjacent to the first ford located approximately 1.5km upstream of Highway 43) as well as at areas upstream (Reach 4 and Reach 5) if the crossing at the highway were to be replaced with a bridge.  Coordinate with other programs in the watershed to help determine the best locations for loggers, contribute data to regional databases and leverage/improve temperature modelling in the region. 
  
  * To quantify habitat quality further up in the watershed collect detailed fish habitat information in Reach 4.
  
  * To build an understanding of spawning cutthrout use and timing within the system conduct redd surveys in the spring/summer of 2023.
  
  * To quantify flow characteristics and help build an understanding of how discharge and spawning timing relate to access through the highway crossing, build a stage discharge curve for the watershed.


## Brule Creek - PSCIS crossings 197533 and 197559

The waterfall located upstream from Highway 43 limits the amount of potential habitat gained by remediation of stream crossing structures on Busato Road and Highway 43 to 3.6km. Although potentially a result of aggredation related to the Highway 43 culverts and road alignement, the seasonal dewatering  in the first 300 - 500m of habitat immediately upstream of Highway 43 (May 5 - October 15 in 2023) is not a desirable habitat characteristic with potential implications for fish stranding.  However, the presence of numerous mountain whitefish and westslope cutthrout trout holding in outlet pools downstream of both Bosato Road and Highway 43 indicate that fish use of the area upstream would likely occur if the culvert barriers are removed. 

<br>

As cold water temperatures could be limiting within stream habitats upstream of the Highway with effects likely increasing in severity with elevation rise, the amount of habitat viable for westslope cutthrout trout may not be any greater (or could in fact be even less) than the 3.6km of habitat present before the falls. 

<br>



Recommendations going forward include:

  * Collection of temperature data at points known to support westslope cutthrout trout (ie. within the outlet pools of Bosato Road and Highway 43 culverts) as well as at areas of potential access (below the falls at 3.6km) if fish passage were to be remediated at the sites.

  * Capture and pit tagging of fish holding in the pools below Highway 43 and transplanting to underneath the falls at 3.6km.  Following one or two growing seasons, attempts could be made to recapture these fish from the vicinity of where they have been transplanted.  This would provide valuable insight into fish movement as well as the ability of upstream habitats to support westsloope cutthrout rearing and overwintering.
  
  * Remove the Busato Road crossing and restore riparian areas between the two roads to a more functional state would be a cost effective solution to resolve passage into and increase the value of the 125m of habitat located between the two crossings.  Access to all areas adjacent to Busato Road would not be significantly impacted by removal of the culvert as traffic can access either end of Busato Road from Highway 43.  A stepped approach to restoration on this stream would provide opportunities to understand fish movement and haiatat suitability through pit tagging and recapture of fish relocated from areas of construction site salvage to upstream of the Highway as well as downstream of Busato Road. At the time of 2022 surveys, riparian areas between the two roads were heavily degraded and fish passage remediation works at Busato Road would provide opportunities for improvement of soils and riparian vegetation that would have benefits for downstream populations.  In addition, restoration of this first piece of stream would help build momentum for works upstream and build awareness for riparian health issues related to range use of the land adjacent to the stream present on private lands both upstream of Highway 43 and downstream of Busato Road. 
  
  * To quantify habitat quality further up in the watershed collect detailed fish habitat information in Reach 4.



